server:
  port: ${CDB_API_REGISTRY_PORT:8082}

spring:
  application:
    name: ${CDB_API_REGISTRY_NAME:cdb-api-registry}
  
  datasource:
    url: ${CDB_API_REGISTRY_DB_URL:${CDB_DB_URL:jdbc:mysql://${CDB_DB_HOST:localhost}:${CDB_DB_PORT:3306}/cdb_api_registry_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
    username: ${CDB_API_REGISTRY_DB_USERNAME:${CDB_DB_USERNAME:root}}
    password: ${CDB_API_REGISTRY_DB_PASSWORD:${CDB_DB_PASSWORD:root}}
    driver-class-name: ${CDB_API_REGISTRY_DB_DRIVER:${CDB_DB_DRIVER:com.mysql.cj.jdbc.Driver}}
  
  jpa:
    hibernate:
      ddl-auto: ${CDB_API_REGISTRY_JPA_DDL_AUTO:none}

logging:
  level:
    root: ${CDB_API_REGISTRY_ROOT_LOG_LEVEL:INFO}

  pattern:
    console: ${CDB_API_REGISTRY_LOG_PATTERN:%d{yyyy-MM-dd HH:mm:ss} - %msg%n}
    file: ${CDB_API_REGISTRY_LOG_FILE_PATTERN:%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n}
  file:
    name: ${CDB_API_REGISTRY_LOG_FILE:cdb-logs/cdb-api-registry/cdb-api-registry.log}
  logback:
    rollingpolicy:
      max-file-size: ${CDB_API_REGISTRY_LOG_MAX_FILE_SIZE:10MB}
      max-history: ${CDB_API_REGISTRY_LOG_MAX_HISTORY:30}
      total-size-cap: ${CDB_API_REGISTRY_LOG_TOTAL_SIZE_CAP:1GB}

