version: '3.8'

services:
  cdb-frontend:
    image: cdb/cdb-frontend:1.0.0
    container_name: cdb-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - cdb
    restart: unless-stopped
    environment:
      - NGINX_HOST=cdb.platformcommons.org
      - NGINX_PORT=443
networks:
  cdb:
    external: true